apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault-secrets-operator
  namespace: vso
spec:
  interval: 10m
  chart:
    spec:
      chart: vault-secrets-operator
      version: 0.10.0
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
  install:
    crds: Skip
  upgrade:
    crds: Skip
  values:
    replicaCount: 1
    defaultVaultConnection:
      enabled: false