---
apiVersion: v1
kind: Namespace
metadata:
  name: elastic-stack
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
  namespace: elastic-stack
spec:
  version: 9.2.0
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
    podTemplate:
      metadata:
        labels:
          scrape: es
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
  namespace: elastic-stack
spec:
  version: 9.2.0
  count: 1
  elasticsearchRef:
    name: quickstart
  podTemplate:
    metadata:
      labels:
        scrape: kb
  http:
    service:
      spec:
        type: NodePort
        ports:
          - protocol: TCP
            nodePort: 30443
            port: 5601
---
apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-server-quickstart
  namespace: elastic-stack
spec:
  version: 9.2.0
  count: 1
  elasticsearchRef:
    name: quickstart
  kibanaRef: 
    name: quickstart
  podTemplate:
    spec: 
      containers:
        - name: apm-server
          env:
            - name: "ES_PASSWORD"
              valueFrom:
                secretKeyRef: 
                  key: elastic
                  name: quickstart-es-elastic-user