---
# mariadb namespace
apiVersion: v1
kind: Namespace
metadata:
  name: mariadb
---
# mariadb-instance
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-instance
  namespace: mariadb
spec:
  replicas: 1

  # Enterprise operator requires a single string
  # https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/docker.md
  image: mariadb:11.8.2

  # Enterprise operator uses "storage" not volumeClaimTemplate
  storage:
    size: 5Gi
---
# VaultStaticSecret that pulls mariadb-admin/root credentials from Vault
# Assumes:
#   - Vault KV v2 mount: kvv2
#   - Path: kvv2/mariadb/admin
#   - Data key: mariadb-root-password
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mariadb-admin
  namespace: mariadb
spec:
  vaultAuthRef: vso/static-auth
  mount: kvv2
  path: mariadb/admin
  type: kv-v2
  refreshAfter: 1h
  hmacSecretData: true
  destination:
    name: mariadb-admin
    create: true
    overwrite: true
---
# mariadb-user
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: admin-user
  namespace: mariadb
spec:
  mariaDbRef:
    name: mariadb-instance

  passwordSecretKeyRef:
    name: mariadb-admin
    key: password

  host: "%"
---
# mariadb-database
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: wordpress-db
  namespace: mariadb
spec:
  mariaDbRef:
    name: mariadb-instance