---
apiVersion: v1
kind: Namespace
metadata:
  name: mariadb
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-basic
  namespace: mariadb
spec:
  replicas: 1
  image:
    repository: mariadb
    tag: "11.4"
  storage:
    size: 5Gi

