---
apiVersion: v1
kind: Namespace
metadata:
  name: mariadb
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-basic
  namespace: mariadb
spec:
  replicas: 1

  # Enterprise operator requires a single string
  image: mariadb:11.4

  # Enterprise operator uses "storage" not volumeClaimTemplate
  storage:
    size: 5Gi