apiVersion: v1
kind: Namespace
metadata:
  name: mariadb
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secrets
  namespace: mariadb
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: supersecurepassword
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: wordpress-mariadb
  namespace: mariadb
spec:
  # Resource requests and limits
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

  # Root password reference (immutable, must be stable)
  rootPasswordSecretKeyRef:
    name: mariadb-secrets
    key: MARIADB_ROOT_PASSWORD

  # Storage
  storage:
    size: 1Gi

  # Number of replicas
  replicas: 1

  # Replication settings
  replication:
    syncBinlog: 1


  # Service exposure
  service:
    type: ClusterIP

  # Optional probes (only those supported by CRD schema)
  livenessProbe:
    exec:
      command:
        - mysqladmin
        - ping
    initialDelaySeconds: 30
    periodSeconds: 10
  readinessProbe:
    exec:
      command:
        - mysqladmin
        - ping
    initialDelaySeconds: 5
    periodSeconds: 10
