---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MaxScale
metadata:
  name: maxscale-galera
  namespace: mariadb
spec:
  replicas: 2
  mariaDbRef:
    name: mariadb-galera
  admin:
    port: 8989
    guiEnabled: true
  monitor:
    name: mariadb-monitor
    module: galeramon
    interval: 2s
    cooperativeMonitoring: majority_of_all
    params:
      disable_master_failback: 'false'
      available_when_donor: 'false'
      disable_master_role_setting: 'false'
  config:
    sync:
      database: mysql
      interval: 5s
      timeout: 10s
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-galera
  namespace: mariadb
spec:
  maxScaleRef:
    name: maxscale-galera
  galera:
    enabled: true
    config:
      reuseStorageVolume: true
    agent:
      basicAuth:
        enabled: true
  replicas: 3
  storage:
    size: 1Gi
  database: mariadb
  username: mariadb
  passwordSecretKeyRef:
    name: mariadb
    key: mariadb-password
