apiVersion: v1
kind: Namespace
metadata:
  name: mariadb
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mariadb
  namespace: mariadb
spec:
  encryptedData:
    password: AgBdmZSwsG2e/e1CuC2p8L6xa4tb5N9WXtJbbRbHunM4EvZIA2rHhgPvwF81uwFp9cm8xLt29V9jabmkWSsHk3NBgHI/AhAHlW8swQr9YbVxhjCLYoSfAWW7rvBG+JtqI/7ZtZ+rKYYCqlt0JGFZ2tI3C0Ihuq7xhlP50qZLAHoC5dSQpsZNOFAXmMt8tlpwxj7VQctxfq78UrBxHuQpNgLgGNpvsHz0TFjoKjsRcIE9S3+rYgaiYqF4Rta63iLftgnBA1yIms/8cH4JbedZngH+GldM1chyF+u+Cx3E2AcVeDqQfpjZ+KkvLv08f2P6Zwf4R87gyTJkpRhaMNcNLu0Cnq5r9wDfUp1sDd9rqC0X+M85IGqZpx6euI2ZA8dru13VjoS4L6tvMnmy112ybyYsLhGdt7NAWg2f6lhmX8zIAh8POc54WOrtWnZNbGP9fM0R+cA36XlOiZfp3KPbX/wPo+Qyjkw9e3CkoNfCNbbEJ8aZqVaNKUsQRG5Wcvym8+knsb7I0sdnxpJsYBy7WhwliiBuOhkpDZWR+/0AaQVD7nYMg7Fy1lxO3DXG69ZdFhJLYQLqzkj+W56YqJq78PkKD7sdDVwe5GkR0OKC8HHMmZ0erW/8Ls23Oa7svPHwCVNWte3cBe9rVNEbUZbpvLqbUtzPH8QvvNegnmHFmYD6Qu5XNqKZQCdWE6YjyClIQd9OWwvHn72hmYpz
  template:
    metadata:
      creationTimestamp: null
      name: mariadb
      namespace: mariadb
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: wordpress-mariadb
  namespace: mariadb
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: password
    generate: false

  storage:
    size: 1Gi

  replicas: 3

  replication:
    enabled: true

  primaryService:
    type: ClusterIP

  secondaryService:
    type: ClusterIP  

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 256Mi