---
apiVersion: v1
kind: Namespace
metadata:
  name: elastic-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: elastic
  namespace: elastic-system
spec:
  interval: 120m
  url: https://helm.elastic.co
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: elastic-operator
  namespace: elastic-system
spec:
  releaseName: elastic-operator
  chart:
    spec:
      chart: eck-operator
      version: 3.2.0
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: elastic-system
  interval: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  # Default values: https://github.com/elastic/cloud-on-k8s/blob/main/deploy/eck-operator/values.yaml
  values:
    image:
      fips: true # adherence to FIPS 140-2
    installCRDs: true
    config:
      validateStorageClass: false