---
apiVersion: v1
kind: Namespace
metadata:
  name: mariadb-operator
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: mariadb-operator
  namespace: flux-system
spec:
  interval: 1h
  url: https://mariadb-operator.github.io/mariadb-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-operator-crds
  namespace: flux-system
spec:
  releaseName: mariadb-operator-crds
  chart:
    spec:
      chart: mariadb-operator-crds
      version: "0.38.0"   # pin to latest
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
        namespace: flux-system
  interval: 5m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-operator
  namespace: mariadb-operator
spec:
  chart:
    spec:
      chart: mariadb-operator
      version: "0.38.0"   # pin to the CRDs chart version
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
        namespace: flux-system
  interval: 1h0m0s
  values:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    webhook:
      cert:
        certManager:
          enabled: true
      serviceMonitor:
        enabled: true