---
apiVersion: v1
kind: Namespace
metadata:
  name: mariadb-operator
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: mariadb-operator
  namespace: flux-system
spec:
  interval: 1h
  url: https://mariadb-operator.github.io/mariadb-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-operator-crds
  namespace: mariadb-operator
spec:
  interval: 10m
  releaseName: mariadb-operator-crds
  chart:
    spec:
      chart: mariadb-operator-crds
      version: "25.10.2" # CalVer Year.Month.Patch
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
        namespace: flux-system
  install:
    createNamespace: true
  upgrade:
    remediation:
      retries: 3
  values: {}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-operator
  namespace: mariadb-operator
spec:
  interval: 10m
  releaseName: mariadb-operator
  dependsOn:
    - name: mariadb-operator-crds
      namespace: mariadb-operator
  chart:
    spec:
      chart: mariadb-operator
      version: "25.10.2" # CalVer Year.Month.Patch
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
        namespace: flux-system
  upgrade:
    remediation:
      retries: 3
  values: {}