---
apiVersion: v1
kind: Namespace
metadata:
  name: minio-operator
---
# minio-helm-repo.yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: minio-operator
  namespace: flux-system
spec:
  interval: 1h
  url: https://operator.min.io
---
# minio-operator-release.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: minio-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: operator
      version: "5.0.10"  # or latest compatible version
      sourceRef:
        kind: HelmRepository
        name: minio-operator
        namespace: flux-system
  values:
    operator:
      console:
        enabled: true