---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: opentelemetry-operator
  namespace: observability
spec:
  interval: 120m
  url: url: https://open-telemetry.github.io/opentelemetry-helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: edot-values
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://raw.githubusercontent.com/elastic/elastic-agent/refs/tags/v9.2.0/deploy/helm/edot-collector/kube-stack
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-kube-stack
  namespace: observability
spec:
  interval: 5m
  chart:
    spec:
      chart: opentelemetry-kube-stack
      version: 0.11.1 # or latest available
      sourceRef:
        kind: HelmRepository
        name: opentelemetry
        namespace: flux-system
  values:
    clusterName: your-cluster-name
    kubeletScraping:
      enabled: true
    daemonSet:
      enabled: true
    otlpReceiver:
      enabled: true