---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: opentelemetry-operator
  namespace: observability
spec:
  interval: 120m
  url: https://open-telemetry.github.io/opentelemetry-helm-charts
---
# Git repository for EDOT values file
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: edot-configs
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/acrilly/observability-configs.git
---
apiVersion: v1
kind: Secret
metadata:
  name: elastic-secret-otel
  namespace: observability
type: Opaque
stringData:
  elastic_endpoint: "https://quickstart-es-http.elastic-stack.svc:9200"
  elastic_api_key: SUswelU1b0JtZS1kck9FUUw3aU46ZHdTWVZfWl9ub2JkV2ZxR29kLWYwUQ==
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-kube-stack
  namespace: observability
spec:
  interval: 5m
  chart:
    spec:
      chart: opentelemetry-kube-stack
      version: 0.11.1 # or latest available
      sourceRef:
        kind: HelmRepository
        name: opentelemetry
        namespace: flux-system
  valuesFrom:
    - kind: GitRepository
      name: edot-configs
      namespace: flux-system
      valuesKey: edot/values.yaml