---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: opentelemetry
  namespace: observability
spec:
  interval: 1h
  url: https://open-telemetry.github.io/opentelemetry-helm-charts
---
apiVersion: v1
kind: Secret
metadata:
  name: elastic-secret-otel
  namespace: observability
type: Opaque
stringData:
  elastic_endpoint: 'https://quickstart-es-http.elastic-stack.svc:9200' 
  elastic_api_key: 'aW5RUndKb0JzX2hLNEo2QVFCaUI6MFV6YWpDQmU3WXBlWGhSUHZGdHR4dw==' # base64 encoded 'elastic:changeme'
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-kube-stack
  namespace: observability
spec:
  interval: 1m
  chart:
    spec:
      chart: opentelemetry-kube-stack
      version: 0.10.5
      sourceRef:
        kind: HelmRepository
        name: opentelemetry
        namespace: observability
  valuesFrom:
  - kind: ConfigMap
    name: otel-values
    valuesKey: values.yaml
