---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: opentelemetry
  namespace: observability
spec:
  interval: 1h
  url: https://open-telemetry.github.io/opentelemetry-helm-charts
---
# Create ConfigMap from EDOT values file
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-values
  namespace: observability
data:
  values.yaml: |
    clusterName: my-cluster
    kubeletScraping:
      enabled: true
    elastic_endpoint: "https://192.168.0.152:9200"
    elastic_api_key: "TXEwZlZwb0JtZS1kck9FUTJiaW46STB4cVBPWktVdzNyblFDNTBIekU1QQ=="
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-kube-stack
  namespace: observability
spec:
  interval: 5m
  chart:
    spec:
      chart: opentelemetry-kube-stack
      version: 0.11.1
      sourceRef:
        kind: HelmRepository
        name: opentelemetry
        namespace: observability
  valuesFrom:
    - kind: ConfigMap
      name: otel-values
      valuesKey: values.yaml
