---
apiVersion: v1
kind: Namespace
metadata:
  name: rabbitmq-system
---
# rabbitmq-oci-chart.yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmChart
metadata:
  name: rabbitmq-cluster-operator
  namespace: flux-system
spec:
  chart: oci://registry-1.docker.io/bitnamicharts/rabbitmq-cluster-operator
  interval: 1h
---
# rabbitmq-operator-release.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rabbitmq-operator
  namespace: rabbitmq-system
spec:
  interval: 5m
  chart:
    spec:
      chart: rabbitmq-cluster-operator
      sourceRef:
        kind: HelmChart
        name: rabbitmq-cluster-operator
        namespace: flux-system
  values:
    replicaCount: 1
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
