---
apiVersion: v1
kind: Namespace
metadata:
  name: strimzi
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: strimzi
  namespace: strimzi
spec:
  interval: 120m
  url: https://strimzi.io/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: strimzi-kafka-operator
  namespace: strimzi
spec:
  releaseName: strimzi-kafka-operator
  chart:
    spec:
      chart: strimzi-kafka-operator
      sourceRef:
        kind: HelmRepository
        name: strimzi
        namespace: strimzi
  interval: 15m
  timeout: 15m0s
  install:
    crds: Skip
    remediation:
      retries: 3
  upgrade:
    crds: Skip
  # Defaults: https://github.com/strimzi/strimzi-kafka-operator/blob/main/helm-charts/helm3/strimzi-kafka-operator/values.yaml
  values:
    watchAnyNamespace: true