---
apiVersion: v1
kind: Namespace
metadata:
  name: vault
---
# vault-helm-repo.yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: hashicorp
  namespace: flux-system
spec:
  interval: 1h
  url: https://helm.releases.hashicorp.com
---
# vault-operator-release.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 5m
  chart:
    spec:
      chart: vault
      version: "0.27.0"  # or latest stable
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
  values:
    global:
      enabled: true
    injector:
      enabled: true
    server:
      enabled: false  # Only deploy the operator, not the Vault server
