---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: dev-team
  name: apps # namespace for dev-team tenant

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: dev-team
  name: dev-team # service account for dev-team tenant
  namespace: apps

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: dev-team
  name: gotk-reconciler # rolebinding for flux reconciler in dev-team tenant
  namespace: apps
roleRef: 
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole 
  name: cluster-admin 
subjects: 
- kind: User 
  name: gotk:apps:reconciler 
- kind: ServiceAccount
  name: dev-team
  namespace: apps
