apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: directpv-min-io
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: minio-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: operator
      version: "5.0.12"   # pin a version for reproducibility
      sourceRef:
        kind: HelmRepository
        name: minio-operator
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
    crds: Create
  upgrade:
    remediation:
      retries: 3
    crds: CreateReplace
  values:
    # Recommended defaults
    operator:
      replicaCount: 1
    console:
      enabled: true
      replicaCount: 1
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-operator-console
  namespace: minio-operator
spec:
  rules:
    - host: minio-console.leclub.org.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: console
                port:
                  number: 9090