---
apiVersion: v1
kind: Namespace
metadata:
  name: elastic-stack
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elastic-tls-secret
  namespace: elastic-stack
spec:
  secretName: elastic-tls-secret
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - Cluster CA
  commonName: elasticsearch-es-http
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - 'elasticsearch-es-http.elastic-stack.es.local'
    - 'elasticsearch-es-http'
    - 'elasticsearch-es-http.elastic-stack.svc'
    - 'elasticsearch-es-http.elastic-stack'
    - 'elasticsearch-es-internal-http.elastic-stack.svc'
    - 'elasticsearch-es-internal-http.elastic-stack'
    - '*.elasticsearch-es-default.elastic-stack.svc'
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: elastic-stack
spec:
  version: 9.2.1
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
    podTemplate:
      metadata:
        labels:
          scrape: es
  http:
    tls:
      certificate:
        secretName: elastic-tls-secret
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic-stack
spec:
  version: 9.2.1
  count: 1
  elasticsearchRef:
    name: elasticsearch
  podTemplate:
    metadata:
      labels:
        scrape: kb
  http:
    service:
      spec:
        type: NodePort
        ports:
          - protocol: TCP
            nodePort: 30443
            port: 5601
---
apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-server
  namespace: elastic-stack
spec:
  version: 9.2.1
  count: 1
  elasticsearchRef:
    name: elasticsearch
  kibanaRef: 
    name: kibana
  podTemplate:
    spec: 
      containers:
        - name: apm-server
          env:
            - name: "ES_PASSWORD"
              valueFrom:
                secretKeyRef: 
                  key: elastic
                  name: elasticsearch-es-elastic-user