apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: directpv
  namespace: flux-system
spec:
  interval: 10m
  path: "./infrastructure/directpv"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true