---
# Deploy cert-manager
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 5m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./infrastructure/core
  prune: true
  wait: true
---
# Deploy Kyverno
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: kyverno
#  namespace: flux-system
#spec:
#  interval: 720m0s
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#  serviceAccountName: kustomize-controller
#  path: ./infrastructure/kyverno
#  prune: true
#  wait: true
#  timeout: 10m
#---
# Deploy Kyverno policies
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: kyverno-policies
#  namespace: flux-system
#spec:
#  dependsOn:
#    - name: kyverno
#  interval: 15m0s
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#  serviceAccountName: kustomize-controller
#  path: ./infrastructure/kyverno-policies
#  prune: true
#---
# Deploy infrastructure operators
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-operators # change here
  namespace: flux-system
spec:
  dependsOn:
    - name: core
  interval: 1h
  retryInterval: 5m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./infrastructure/operators # and here
  prune: true
  wait: true
---
# Deploy infrastructure tools
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-tools # change here
  namespace: flux-system
spec:
  dependsOn:
    - name: core
  interval: 1h
  retryInterval: 5m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./infrastructure/tools # and here
  prune: true
  wait: true
  patches:
    - patch: |
        - op: replace
          path: /spec/values/ingress/hosts/0/host
          value: "dashboard.leclub.org.uk"
      target:
        kind: HelmRelease
        name: ww-gitops
---
# Deploy Elastic Stack
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: elastic-cluster
#  namespace: flux-system
#spec:
#  dependsOn:
#    - name: infra-operators
#  interval: 10m0s
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#  serviceAccountName: kustomize-controller
#  path: ./infrastructure/elastic
#  prune: true
---
# Deploy CloudNativePG Cluster
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: cnpg-cluster
#  namespace: flux-system
#spec:
#  dependsOn:
#    - name: infra-operators
#    - name: infra-tools
#    - name: core
#  interval: 10m0s
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#  serviceAccountName: kustomize-controller
#  path: ./infrastructure/cnpg
#  prune: true
---
# Deploy MinIO Tenant
---
# Deploy MariaDB Clusters
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mariadb-cluster
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-operators
    - name: infra-tools
    - name: core
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./infrastructure/mariadb
  prune: true