# Deploy MariaDB Clusters
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mariadb-cluster
  namespace: flux-system
spec:
  dependsOn:
    - name: vso-operator
    - name: mariadb-operator
    - name: vso-auth
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  path: ./infrastructure/mariadb
  prune: true