apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mariadb-instance
  namespace: flux-system
spec:
  dependsOn:
    - name: mariadb-operator
  interval: 10m
  path: ./infrastructure/operators/mariadb-instance
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system