apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minio-crds
  namespace: flux-system
spec:
  dependsOn:
    - name: minio-repo
    - name: minio-namespace
  interval: 10m
  path: ./infrastructure/operators/minio-crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system