apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vso-namespace
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/operators/vso-namespace
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m