---
apiVersion: v1
kind: Namespace
metadata:
  name: elastic-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: elastic
  namespace: elastic-system
spec:
  interval: 120m
  url: https://helm.elastic.co
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: elastic-operator
  namespace: elastic-system
spec:
  releaseName: elastic-operator
  chart:
    spec:
      chart: eck-operator
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: elastic-system
  interval: 15m
  install:
    remediation:
      retries: 3
  # Default values: https://github.com/elastic/cloud-on-k8s/blob/main/deploy/eck-operator/values.yaml
  values:
    installCRDs: true
    config:
      validateStorageClass: false
---
apiVersion: v1
kind: Namespace
metadata:
  name: elastic-stack
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
  namespace: elastic-stack
spec:
  version: 9.2.0
  nodeSets:
  - name: default
    count: 2
    config:
      node.store.allow_mmap: false
    podTemplate:
      metadata:
        labels:
          scrape: es
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
  namespace: elastic-stack
spec:
  version: 9.2.0
  count: 1
  elasticsearchRef:
    name: quickstart
  podTemplate:
    metadata:
      labels:
        scrape: kb
  http:
    service:
      spec:
        type: NodePort
        ports:
          - protocol: TCP
            nodePort: 30443
            port: 5601