---
apiVersion: v1
kind: Namespace
metadata:
  name: pgadmin
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: runix
  namespace: pgadmin
spec:
  interval: 120m
  url: https://helm.runix.net
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pgadmin4
  namespace: pgadmin
spec:
  releaseName: pgadmin4
  chart:
    spec:
      chart: pgadmin4
      sourceRef:
        kind: HelmRepository
        name: runix
        namespace: pgadmin
  interval: 5m
  install:
    remediation:
      retries: 3
  # Defaults: https://github.com/rowanruseler/helm-charts/blob/main/charts/pgadmin4/values.yaml
  # values: