---
apiVersion: v1
kind: Namespace
metadata:
  name: pgadmin
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: runix
  namespace: pgadmin
spec:
  interval: 120m
  url: https://helm.runix.net
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pgadmin4
  namespace: pgadmin
spec:
  releaseName: pgadmin4
  chart:
    spec:
      chart: pgadmin4
      version: 1.49.0
      sourceRef:
        kind: HelmRepository
        name: runix
        namespace: pgadmin
  values:
    env:
      email: "andrew.crilly@live.co.uk"
      password: "admin"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.entrypoints: web
      hosts:
        - host: pgadmin.staging
          paths:
            - path: /
              pathType: Prefix
    persistentVolume:
      enabled: true
      size: 1Gi
  interval: 7m
  install:
    remediation:
      retries: 3
  # Defaults: https://github.com/rowanruseler/helm-charts/blob/main/charts/pgadmin4/values.yaml
  # values: