---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: postgresql
  namespace: default
spec:
  type: oci
  interval: 7m0s
  url: oci://registry-1.docker.io/bitnamicharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: default
spec:
  serviceAccountName: kustomize-controller
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: "16.7.0"
      sourceRef:
        kind: HelmRepository
        name: postgresql
        namespace: default
      interval: 1m
  values:
    global:
      security:
        allowInsecureImages: true
    image:
      repository: bitnamilegacy/postgresql
    volumePermissions:
      image:
        repository: bitnamilegacy/os-shell
    metrics:
      image:
        repository: bitnamilegacy/postgresql-exporter
    auth:
      username: "myuser"
      password: "mypassword"
      database: "mydatabase"
