---
apiVersion: v1
kind: Namespace
metadata:
  name: harbor
---
# harbor-helm-repo.yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: harbor
  namespace: flux-system
spec:
  interval: 1h
  url: https://helm.goharbor.io
---
# harbor-release.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 5m
  chart:
    spec:
      chart: harbor
      version: "1.14.0"  # Replace with latest stable version
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
  values:
    expose:
      type: ingress
      tls:
        enabled: true
        secretName: harbor-tls
      ingress:
        hosts:
          core: harbor.example.com
          notary: notary.harbor.example.com
        annotations:
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
    externalURL: https://harbor.example.com
    harborAdminPassword: "YourSecurePassword"
