# namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: kube-state-metrics
  labels:
    app: kube-state-metrics
---
# helmrepository.yaml
# helmrepository.yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  interval: 1h0m
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-state-metrics
  namespace: kube-state-metrics
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-state-metrics
      version: "6.4.1"           # pick a suitable chart version for your cluster
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    replicaCount: 1
    rbac:
      create: true
    metrics:
      enabled: true
    service:
      port: 8080
    serviceMonitor:
      enabled: false   # set true if you use Prometheus Operator and want a ServiceMonitor; change namespace accordingly

