# mariadb-user
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: admin-user
  namespace: mariadb
spec:
  mariaDbRef:
    name: mariadb-instance

  passwordSecretKeyRef:
    name: mariadb-admin
    key: password

  host: "%"