# infrastructure/operators/mariadb-instance/vaultstaticsecret-mariadb-admin.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mariadb-admin
  namespace: mariadb
spec:
  mount: kvv2
  path: mariadb/admin
  type: kv-v2
  refreshAfter: 1h
  vaultAuthRef: static-auth
  destination:
    create: true
    name: mariadb-admin
    overwrite: true
  hmacSecretData: true