apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mariadb-admin
  namespace: mariadb
spec:
  mount: kvv2
  path: mariadb/admin
  type: kv-v2

  vaultAuthRef: static-auth

  destination:
    name: mariadb-admin
    create: true
    overwrite: true