# infrastructure/operators/mariadb-instance/vaultauth-static.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth
  namespace: mariadb
spec:
  method: kubernetes
  mount: staging-auth-mount
  vaultConnectionRef: vault-conn

  kubernetes:
    role: vso-role
    serviceAccount: vault-sa
    audiences:
      - vault

  allowedNamespaces:
    - mariadb