apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-operator
  namespace: mariadb-operator
spec:
  interval: 10m
  chart:
    spec:
      chart: mariadb-operator
      version: "25.10.2"
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator-repo
        namespace: flux-system
  install:
    createNamespace: false
  upgrade:
    remediation:
      retries: 3
  values:
    operator:
      enabled: true